# -*- coding: utf-8 -*-
# Cápsulas de cocina de Celestia. Cada artículo tiene versión ES y EN.
# Bloques: ("p", texto) · ("h2", texto) · ("ul", [items]) · ("ol", [items])
#          ("tabla", [encabezados], [[fila], ...]) · ("tip", texto) · ("dato", texto)

CATS = {
    "cortes":   {"es": "Cortes y técnica", "en": "Knife work & technique", "icono": "🔪"},
    "salsas":   {"es": "Salsas",           "en": "Sauces",                 "icono": "🥄"},
    "carnes":   {"es": "Carnes",           "en": "Meat",                   "icono": "🥩"},
    "emplatado":{"es": "Emplatado",        "en": "Plating",                "icono": "✨"},
    "recetas":  {"es": "Recetas con toque de chef", "en": "Recipes with a chef's touch", "icono": "🍳"},
}

ARTICULOS = [
# ───────────────────────────────────────────────────────────────────────────
dict(slug="cortes-de-cuchillo-y-coccion", cat="cortes", fecha="2026-10-08",
 img="photo-1492739159057-7d1896b3c63f", foto="Caroline Attwood",
 es=dict(
  titulo="Cortes de cuchillo: cómo el corte define la cocción",
  bajada="Brunoise, juliana, mirepoix… no es un capricho de escuela: el tamaño del corte decide cuánto tarda, cuánto sabor suelta y cómo se ve el plato.",
  cuerpo=[
   ("p","Una misma zanahoria puede deshacerse en una salsa o quedar firme en un guiso de cuatro horas. La diferencia no está en el fuego: está en el cuchillo. Cuanto más chico el corte, más superficie expuesta al calor, más rápido se cocina y más sabor entrega al líquido."),
   ("h2","Los cortes clásicos y para qué sirve cada uno"),
   ("tabla",["Corte","Medida aproximada","Ideal para"],[
     ["Brunoise","Cubos de 2 a 3 mm","Salsas, sofritos delicados, terminaciones"],
     ["Macedonia","Cubos de 5 mm","Ensaladas, rellenos, guarniciones"],
     ["Parmentier","Cubos de 1 a 1,2 cm","Papas salteadas, guisos"],
     ["Juliana","Bastones de 2 mm × 5 cm","Salteados rápidos, wok, decoración"],
     ["Bastón","Bastones de 6 mm × 6 cm","Crudités, papas fritas"],
     ["Paysanne","Láminas de 1 × 1 cm, finas","Sopas y cocciones cortas"],
     ["Chiffonade","Tiras muy finas de hojas","Albahaca, espinaca, terminación"],
     ["Mirepoix","Trozos de 1 a 2 cm","Fondos, caldos y braseados largos"],
   ]),
   ("dato","Las medidas varían un poco según la escuela; lo importante es la lógica: cocción larga, corte grande; cocción corta, corte chico."),
   ("h2","La regla de oro: cocción larga, corte grande"),
   ("p","Para un fondo que hierve horas, el mirepoix grande suelta sabor de a poco y no se deshace. Si usaras brunoise, a la media hora sería puré y el caldo quedaría turbio. Al revés, en un salteado de dos minutos solo llegan a cocinarse la juliana o la brunoise."),
   ("tip","Uniformidad antes que velocidad. Si todos los cubos miden lo mismo, todos se cocinan al mismo tiempo. Cortá primero en láminas parejas, después en bastones y recién ahí en cubos: así salen iguales sin esfuerzo."),
   ("h2","Errores que delatan al cocinero apurado"),
   ("ul",["Cortar en tamaños distintos: unos quedan crudos y otros pasados.",
          "Usar un cuchillo sin filo: aplasta en lugar de cortar y la verdura pierde jugo.",
          "Poner todo junto en la sartén: lo duro (zanahoria) va antes que lo tierno (zucchini).",
          "Olvidar la “garra”: los dedos de la mano que sostiene, curvados hacia adentro, guían la hoja y te protegen."]),
  ]),
 en=dict(
  titulo="Knife cuts: how the cut shapes the cooking",
  bajada="Brunoise, julienne, mirepoix… it isn't culinary-school fussiness: the size of the cut decides how long it takes, how much flavor it releases and how the plate looks.",
  cuerpo=[
   ("p","The same carrot can melt into a sauce or stay firm through a four-hour stew. The difference isn't the heat — it's the knife. The smaller the cut, the more surface exposed to heat, the faster it cooks and the more flavor it gives to the liquid."),
   ("h2","The classic cuts and what each one is for"),
   ("tabla",["Cut","Approximate size","Best for"],[
     ["Brunoise","2–3 mm cubes","Sauces, delicate sofritos, finishing"],
     ["Macédoine","5 mm cubes","Salads, fillings, sides"],
     ["Parmentier","1–1.2 cm cubes","Sautéed potatoes, stews"],
     ["Julienne","2 mm × 5 cm sticks","Quick stir-fries, wok, garnish"],
     ["Bâtonnet","6 mm × 6 cm sticks","Crudités, fries"],
     ["Paysanne","Thin 1 × 1 cm slices","Soups and short cooking"],
     ["Chiffonade","Very thin ribbons of leaves","Basil, spinach, finishing"],
     ["Mirepoix","1–2 cm pieces","Stocks, broths and long braises"],
   ]),
   ("dato","Sizes vary slightly from school to school; what matters is the logic: long cooking, big cut; short cooking, small cut."),
   ("h2","The golden rule: long cooking, big cut"),
   ("p","For a stock that simmers for hours, a large mirepoix releases flavor slowly and doesn't fall apart. With a brunoise it would be mush in half an hour and the stock would turn cloudy. Conversely, in a two-minute stir-fry only a julienne or brunoise has time to cook."),
   ("tip","Consistency before speed. If every cube is the same size, they all cook at the same time. Slice evenly first, then cut into sticks, and only then into cubes: they come out identical without effort."),
   ("h2","Mistakes that give away a rushed cook"),
   ("ul",["Cutting different sizes: some stay raw while others overcook.",
          "Using a dull knife: it crushes instead of cutting and the vegetable loses its juice.",
          "Adding everything at once: hard vegetables (carrot) go in before tender ones (zucchini).",
          "Forgetting the “claw”: the fingers of your holding hand, curled inward, guide the blade and keep you safe."]),
  ])),
# ───────────────────────────────────────────────────────────────────────────
dict(slug="las-5-salsas-madre", cat="salsas", fecha="2026-10-08",
 img="photo-1625631976982-c6df1654a6ea", foto="Vitor Monthay",
 es=dict(
  titulo="Las 5 salsas madre: la base de casi todas las salsas",
  bajada="Dominá cinco salsas y tenés la llave de cientos de variantes. Así las ordenó la cocina francesa y así se siguen enseñando en las escuelas.",
  cuerpo=[
   ("p","A principios del siglo XX, Auguste Escoffier ordenó las salsas de la cocina francesa en cinco “madres”. De cada una nacen las “hijas” o derivadas: cambiás un ingrediente o sumás una terminación y tenés una salsa nueva."),
   ("tabla",["Salsa madre","Base","Espesante","Algunas derivadas"],[
     ["Bechamel","Leche","Roux blanco","Mornay (con queso), Soubise (con cebolla)"],
     ["Velouté","Fondo claro (ave, ternera o pescado)","Roux rubio","Suprema (con crema), Allemande (con yema)"],
     ["Española","Fondo oscuro, mirepoix y tomate","Roux oscuro","Demi-glace, bordelesa"],
     ["Holandesa","Yemas y manteca clarificada","Emulsión","Bearnesa (estragón), Muselina (crema batida)"],
     ["Tomate","Tomate, aromáticos y fondo","Reducción","Provenzal, criolla"],
   ]),
   ("h2","El roux, el secreto de tres de las cinco"),
   ("p","El roux es manteca y harina en igual peso, cocinadas juntas. Según cuánto lo cocines cambia el color y el sabor: blanco (2 a 3 minutos), rubio (unos 5) u oscuro (hasta color avellana). Cuanto más oscuro, más sabor tostado pero menos poder de espesar."),
   ("dato","Como referencia, unos 50 g de manteca y 50 g de harina espesan 1 litro de leche para una bechamel de consistencia media."),
   ("tip","Contraste de temperaturas: roux caliente con líquido frío, o roux frío con líquido caliente. Nunca los dos calientes: es la forma más segura de que no se formen grumos. Batí con batidor, no con cuchara."),
   ("h2","La holandesa, la más delicada"),
   ("p","No lleva harina: es una emulsión de yemas y manteca, como una mayonesa tibia. Se hace a baño María, batiendo las yemas con un poco de agua o reducción hasta que espesan, y sumando la manteca clarificada de a hilo. Si se calienta de más, las yemas se cocinan y se corta."),
   ("tip","Si la holandesa se corta, no la tires: en otro bol poné una yema o una cucharada de agua tibia y volvé a incorporar la salsa cortada de a poco, batiendo. Se recupera."),
   ("h2","Cómo hacerte ver como chef con esto"),
   ("ul",["Una bechamel con un poco de queso rallado al final ya es una Mornay: ideal para gratinar.",
          "Una velouté de ave con crema y unas gotas de limón es una suprema para pollo o pescado.",
          "Una holandesa con estragón, chalota y vinagre reducido es una bearnesa: el clásico para un buen bife."]),
  ]),
 en=dict(
  titulo="The 5 mother sauces: the base of almost every sauce",
  bajada="Master five sauces and you hold the key to hundreds of variations. That's how French cuisine organized them, and it's still how culinary schools teach them.",
  cuerpo=[
   ("p","In the early 20th century, Auguste Escoffier organized the sauces of French cuisine into five “mothers.” Each one gives birth to “daughter” or derivative sauces: change one ingredient or add a finish and you have a new sauce."),
   ("tabla",["Mother sauce","Base","Thickener","Some derivatives"],[
     ["Béchamel","Milk","White roux","Mornay (with cheese), Soubise (with onion)"],
     ["Velouté","Light stock (chicken, veal or fish)","Blond roux","Suprême (with cream), Allemande (with yolk)"],
     ["Espagnole","Brown stock, mirepoix and tomato","Brown roux","Demi-glace, bordelaise"],
     ["Hollandaise","Egg yolks and clarified butter","Emulsion","Béarnaise (tarragon), Mousseline (whipped cream)"],
     ["Tomato","Tomato, aromatics and stock","Reduction","Provençal, creole"],
   ]),
   ("h2","Roux, the secret behind three of the five"),
   ("p","Roux is butter and flour in equal weight, cooked together. How long you cook it changes the color and flavor: white (2 to 3 minutes), blond (about 5) or brown (until hazelnut-colored). The darker it is, the more toasty flavor but the less thickening power."),
   ("dato","As a guide, about 50 g butter and 50 g flour thicken 1 liter of milk for a medium-consistency béchamel."),
   ("tip","Contrast the temperatures: hot roux with cold liquid, or cold roux with hot liquid. Never both hot: it's the surest way to avoid lumps. Use a whisk, not a spoon."),
   ("h2","Hollandaise, the most delicate"),
   ("p","It has no flour: it's an emulsion of yolks and butter, like a warm mayonnaise. It's made over a bain-marie, whisking the yolks with a little water or reduction until they thicken, then adding clarified butter in a thin stream. If it gets too hot, the yolks cook and it splits."),
   ("tip","If your hollandaise splits, don't throw it away: put a yolk or a spoonful of warm water in another bowl and whisk the split sauce back in little by little. It comes back."),
   ("h2","How to look like a chef with this"),
   ("ul",["A béchamel with a little grated cheese at the end is already a Mornay: perfect for gratins.",
          "A chicken velouté with cream and a few drops of lemon is a suprême for chicken or fish.",
          "A hollandaise with tarragon, shallot and reduced vinegar is a béarnaise: the classic for a good steak."]),
  ])),
# ───────────────────────────────────────────────────────────────────────────
dict(slug="ojo-de-bife-sellado-punto-reposo", cat="carnes", fecha="2026-10-08",
 img="photo-1529692236671-f1f6cf9683ba", foto="José Ignacio Pompé",
 es=dict(
  titulo="Ojo de bife: sellado, punto y reposo",
  bajada="Tres decisiones separan un bife común de uno de restaurante: cómo lo sellás, cuándo lo sacás y cuánto lo dejás descansar.",
  cuerpo=[
   ("h2","Antes del fuego"),
   ("ul",["Sacalo de la heladera 30 a 40 minutos antes: si entra helado, se pasa por fuera antes de llegar al punto por dentro.",
          "Secalo bien con papel: la humedad hace que se hierva en lugar de dorarse.",
          "Salá con anticipación (40 minutos o más) o justo antes de cocinar."]),
   ("h2","El sellado"),
   ("p","Sartén de hierro o plancha bien caliente, con un hilo de aceite neutro. El bife tiene que chirriar al apoyarlo. Esa costra dorada es la reacción de Maillard: azúcares y proteínas que se transforman en cientos de compuestos de sabor. No lo muevas hasta que se despegue solo."),
   ("tip","El arroser: en el último minuto bajá el fuego, sumá una cucharada de manteca, un diente de ajo aplastado y una rama de tomillo, inclinás la sartén y lo bañás con la manteca espumosa usando una cuchara. Es el gesto que más sabor suma en menos tiempo."),
   ("h2","El punto, con termómetro"),
   ("p","El tacto engaña; el termómetro no. Medí en el centro de la pieza y retirá del fuego unos 3 °C antes del punto que buscás, porque la temperatura sigue subiendo mientras reposa."),
   ("tabla",["Punto","Temperatura final aproximada","Cómo se ve"],[
     ["Jugoso","52 – 54 °C","Centro rojo y tibio"],
     ["A punto","56 – 58 °C","Centro rosado, jugoso"],
     ["Tres cuartos","60 – 63 °C","Apenas rosado"],
     ["Cocido","65 °C o más","Sin rosado"],
   ]),
   ("h2","El reposo, el paso que todos saltean"),
   ("p","Dejalo descansar 5 a 8 minutos sobre una rejilla o tabla, sin tapar con fuerza. Las fibras se relajan y los jugos se redistribuyen: si lo cortás enseguida, terminan en la tabla y no en el plato."),
   ("tip","Cortá en contra de la fibra, en láminas, y terminá con sal en escamas recién al servir: el crocante de la sal sobre la carne tibia es pura terminación de chef."),
  ]),
 en=dict(
  titulo="Ribeye: sear, doneness and rest",
  bajada="Three decisions separate an ordinary steak from a restaurant one: how you sear it, when you take it off and how long you let it rest.",
  cuerpo=[
   ("h2","Before the heat"),
   ("ul",["Take it out of the fridge 30 to 40 minutes before: if it goes in cold, the outside overcooks before the inside reaches doneness.",
          "Pat it very dry with paper: moisture makes it boil instead of brown.",
          "Salt well ahead (40 minutes or more) or right before cooking."]),
   ("h2","The sear"),
   ("p","A cast-iron pan or griddle, very hot, with a drizzle of neutral oil. The steak should sizzle loudly when it lands. That golden crust is the Maillard reaction: sugars and proteins transforming into hundreds of flavor compounds. Don't move it until it releases on its own."),
   ("tip","Basting (arroser): in the last minute lower the heat, add a spoonful of butter, a crushed garlic clove and a sprig of thyme, tilt the pan and spoon the foaming butter over the steak. It's the gesture that adds the most flavor in the least time."),
   ("h2","Doneness, with a thermometer"),
   ("p","Touch can fool you; a thermometer can't. Measure in the center and take it off the heat about 3 °C before your target, because the temperature keeps rising while it rests."),
   ("tabla",["Doneness","Approximate final temperature","How it looks"],[
     ["Rare","52 – 54 °C","Red, warm center"],
     ["Medium-rare","56 – 58 °C","Pink, juicy center"],
     ["Medium","60 – 63 °C","Barely pink"],
     ["Well done","65 °C or more","No pink"],
   ]),
   ("h2","Resting, the step everyone skips"),
   ("p","Let it rest 5 to 8 minutes on a rack or board, loosely covered at most. The fibers relax and the juices redistribute: cut it right away and they end up on the board instead of on the plate."),
   ("tip","Slice against the grain and finish with flaky salt only when serving: the crunch of salt on warm meat is a true chef's finish."),
  ])),
# ───────────────────────────────────────────────────────────────────────────
dict(slug="emplatar-como-chef", cat="emplatado", fecha="2026-10-08",
 img="photo-1759277513461-41fde7d24083", foto="Madeline Liu",
 es=dict(
  titulo="Emplatar como en un menú de 7 pasos",
  bajada="La comida entra primero por los ojos. Con cinco reglas simples, un plato casero se ve de restaurante.",
  cuerpo=[
   ("ol",["<b>Plato a la temperatura justa.</b> Tibio para lo caliente (unos minutos en el horno apagado), frío para lo frío. Es lo primero que se nota y lo que menos se ve.",
          "<b>Números impares.</b> Tres vieiras se ven mejor que dos o cuatro. Lo impar genera movimiento.",
          "<b>Altura.</b> Apoyá la proteína sobre la guarnición en lugar de al lado: el plato gana volumen y presencia.",
          "<b>Contraste.</b> De color (un verde fresco sobre algo dorado) y de textura (algo crocante sobre algo cremoso).",
          "<b>Espacio vacío.</b> No llenes el plato. El blanco alrededor enmarca la comida y la hace protagonista."]),
   ("h2","La salsa, con cuchara"),
   ("p","Una cucharada de salsa en el plato, y con el dorso de la cuchara arrastrás en un solo movimiento: la clásica lágrima. Otra opción es un punto de salsa al costado de la proteína, nunca encima tapándola si tiene una costra dorada que mostrar."),
   ("tip","Tené a mano una servilleta apenas húmeda y una pinza. Antes de servir, repasá el borde del plato: una gota de salsa o una miga en el borde es lo que separa un plato casero de uno de chef."),
   ("h2","La terminación"),
   ("ul",["Un hilo de buen aceite de oliva o de aceite de hierbas.",
          "Sal en escamas sobre la proteína.",
          "Hojas pequeñas o brotes, con pinza, en dos o tres puntos — no como lluvia.",
          "Ralladura de cítrico justo antes de llevar a la mesa."]),
   ("dato","En un menú por pasos, cada plato se piensa como una composición: el orden, el color y el ritmo de toda la cena importan tanto como cada plato por separado."),
  ]),
 en=dict(
  titulo="Plating like a 7-course tasting menu",
  bajada="We eat with our eyes first. With five simple rules, a home-cooked dish looks restaurant-ready.",
  cuerpo=[
   ("ol",["<b>The right plate temperature.</b> Warm for hot food (a few minutes in a switched-off oven), chilled for cold food. It's the first thing you notice and the least visible.",
          "<b>Odd numbers.</b> Three scallops look better than two or four. Odd numbers create movement.",
          "<b>Height.</b> Rest the protein on top of the side instead of next to it: the plate gains volume and presence.",
          "<b>Contrast.</b> Of color (a fresh green over something golden) and texture (something crunchy over something creamy).",
          "<b>Empty space.</b> Don't fill the plate. The white around it frames the food and makes it the star."]),
   ("h2","Sauce, with a spoon"),
   ("p","A spoonful of sauce on the plate, then drag it with the back of the spoon in one movement: the classic swoosh. Another option is a dot of sauce beside the protein — never on top, hiding a golden crust worth showing."),
   ("tip","Keep a barely damp cloth and tweezers at hand. Before serving, wipe the rim: a drop of sauce or a crumb on the edge is what separates a home plate from a chef's."),
   ("h2","The finish"),
   ("ul",["A drizzle of good olive oil or herb oil.",
          "Flaky salt on the protein.",
          "Small leaves or sprouts, placed with tweezers at two or three points — not scattered like rain.",
          "Citrus zest right before it goes to the table."]),
   ("dato","In a tasting menu, each plate is designed as a composition: the order, color and rhythm of the whole dinner matter as much as each plate on its own."),
  ])),
# ───────────────────────────────────────────────────────────────────────────
dict(slug="reducciones-y-glaseados", cat="salsas", fecha="2026-10-08",
 img="photo-1499126167718-c87f5c1387e8", foto="Caroline Attwood",
 es=dict(
  titulo="Reducciones y glaseados: el brillo de restaurante",
  bajada="Ese brillo espejado de las salsas de restaurante no es magia: es reducción, paciencia y manteca fría al final.",
  cuerpo=[
   ("h2","Desglasar: el sabor está pegado en la sartén"),
   ("p","Después de sellar una carne quedan restos dorados en el fondo de la sartén. Eso es sabor concentrado. Sacá la carne, volcá un chorro de vino, fondo o incluso agua, y raspá con una cuchara de madera mientras hierve: todo ese dorado se disuelve y se convierte en la base de tu salsa."),
   ("h2","Reducir hasta “napar”"),
   ("p","Dejá hervir suave hasta que el líquido se reduzca y tome cuerpo. El punto se llama napar: cuando la salsa cubre el dorso de una cuchara y, si pasás el dedo, la línea queda marcada sin que se junte."),
   ("tip","Salá siempre al final. Al reducir, el agua se evapora pero la sal se queda: si salás al principio, al terminar la salsa puede quedar salada de más."),
   ("h2","Montar con manteca: el toque final"),
   ("p","Fuera del fuego, sumá unos cubos de manteca bien fría y movés la sartén en círculos (o batís suave) hasta que se integren. La salsa gana brillo, cuerpo y una textura sedosa. Los franceses lo llaman monter au beurre."),
   ("dato","La manteca tiene que estar fría y la salsa caliente pero sin hervir: si hierve después de montarla, la emulsión se rompe y la manteca se separa."),
   ("h2","Glaseado de vegetales"),
   ("p","Zanahorias, cebollitas o nabos con agua hasta la mitad, una cucharada de manteca, una pizca de azúcar y sal. Cocinás a fuego medio hasta que el agua se evapora y queda una película brillante que los envuelve. Si los dejás un minuto más, se doran: glaseado oscuro."),
   ("tip","Pasá la salsa por un colador fino antes de servir. Es un paso de diez segundos que la deja lisa y profesional."),
  ]),
 en=dict(
  titulo="Reductions and glazes: restaurant shine",
  bajada="That mirror-like shine of restaurant sauces isn't magic: it's reduction, patience and cold butter at the end.",
  cuerpo=[
   ("h2","Deglazing: the flavor is stuck to the pan"),
   ("p","After searing meat, golden bits are left on the bottom of the pan. That's concentrated flavor. Take the meat out, pour in a splash of wine, stock or even water, and scrape with a wooden spoon as it boils: all that browning dissolves and becomes the base of your sauce."),
   ("h2","Reducing until it “naps”"),
   ("p","Let it simmer until the liquid reduces and gains body. The point is called nappe: when the sauce coats the back of a spoon and, if you run your finger through it, the line stays without closing up."),
   ("tip","Always salt at the end. As it reduces, the water evaporates but the salt stays: salt at the start and the finished sauce may end up too salty."),
   ("h2","Mounting with butter: the final touch"),
   ("p","Off the heat, add a few cubes of very cold butter and swirl the pan (or whisk gently) until they melt in. The sauce gains shine, body and a silky texture. The French call it monter au beurre."),
   ("dato","The butter must be cold and the sauce hot but not boiling: if it boils after mounting, the emulsion breaks and the butter separates."),
   ("h2","Glazed vegetables"),
   ("p","Carrots, pearl onions or turnips with water halfway up, a spoonful of butter, a pinch of sugar and salt. Cook over medium heat until the water evaporates and leaves a shiny film coating them. Give them one more minute and they brown: a dark glaze."),
   ("tip","Strain the sauce through a fine sieve before serving. It's a ten-second step that leaves it smooth and professional."),
  ])),
# ───────────────────────────────────────────────────────────────────────────
dict(slug="pure-de-papas-de-restaurante", cat="recetas", fecha="2026-10-08",
 img="photo-1585508659081-04a1788941c1", foto="Anna Stampfli",
 es=dict(
  titulo="Puré de papas de restaurante",
  bajada="El acompañamiento más simple es también el que más delata la técnica. Cinco claves para un puré liso, sedoso y con sabor.",
  cuerpo=[
   ("h2","Ingredientes (4 porciones)"),
   ("ul",["1 kg de papas harinosas (papa negra, Spunta)",
          "100 a 150 g de manteca bien fría, en cubos",
          "200 ml de leche (o mitad leche, mitad crema)",
          "Sal, pimienta blanca y nuez moscada"]),
   ("h2","Paso a paso"),
   ("ol",["<b>Agua fría y con sal.</b> Poné las papas (enteras con piel o en trozos parejos) en agua fría con sal y llevá a hervor. Si arrancan en agua hirviendo, se cocinan por fuera antes que por dentro.",
          "<b>Cocción justa.</b> Están listas cuando un cuchillo entra sin resistencia. Escurrí bien.",
          "<b>Secarlas.</b> Volvé las papas a la olla y 1 minuto a fuego bajo, moviendo: se evapora el agua que queda y el puré no se aguachenta.",
          "<b>Pisar, nunca licuar.</b> Pasalas por pisapapas o, mejor, por un tamiz. La minipimer rompe el almidón y el puré se vuelve un engrudo elástico.",
          "<b>Primero la manteca, después la leche.</b> Incorporá la manteca fría en cubos, mezclando, y recién después la leche bien caliente de a poco, hasta la textura que te guste. Condimentá al final."]),
   ("tip","Infusioná la leche: calentala con una hoja de laurel y un diente de ajo aplastado, dejá reposar 10 minutos y colá. Usá pimienta blanca en vez de negra para que no se vean puntitos: es un detalle muy de restaurante."),
   ("dato","Las versiones más famosas de restaurante llevan muchísima más manteca: hasta casi la mitad del peso de las papas. Con 100 a 150 g por kilo tenés un puré de lujo, sin exagerar."),
   ("h2","Para servirlo como chef"),
   ("p","Una cucharada generosa en el centro del plato, y con el dorso de la cuchara hacés una curva que deje un surco. Ahí va la salsa o el jugo de la carne. Arriba, un hilo de manteca dorada o de aceite de oliva y unas hojas de cebollín."),
  ]),
 en=dict(
  titulo="Restaurant-style mashed potatoes",
  bajada="The simplest side is also the one that most reveals technique. Five keys to a smooth, silky, flavorful mash.",
  cuerpo=[
   ("h2","Ingredients (4 servings)"),
   ("ul",["1 kg floury potatoes",
          "100 to 150 g very cold butter, cubed",
          "200 ml milk (or half milk, half cream)",
          "Salt, white pepper and nutmeg"]),
   ("h2","Step by step"),
   ("ol",["<b>Cold, salted water.</b> Put the potatoes (whole with skin, or in even pieces) in cold salted water and bring to a boil. If they start in boiling water, the outside cooks before the inside.",
          "<b>Just-right cooking.</b> They're ready when a knife slides in without resistance. Drain well.",
          "<b>Dry them.</b> Return the potatoes to the pot for 1 minute over low heat, stirring: the leftover water evaporates and the mash won't be watery.",
          "<b>Mash, never blend.</b> Use a potato ricer or, better, a sieve. A stick blender breaks the starch and turns the mash gluey and elastic.",
          "<b>Butter first, then milk.</b> Work in the cold butter cubes, then add the very hot milk little by little until you like the texture. Season at the end."]),
   ("tip","Infuse the milk: heat it with a bay leaf and a crushed garlic clove, let it sit 10 minutes and strain. Use white pepper instead of black so there are no specks: a very restaurant detail."),
   ("dato","The most famous restaurant versions use far more butter: up to nearly half the weight of the potatoes. With 100 to 150 g per kilo you get a luxurious mash without going overboard."),
   ("h2","To serve it like a chef"),
   ("p","A generous spoonful in the center of the plate, then sweep a curve with the back of the spoon to leave a groove. That's where the sauce or meat juices go. On top, a drizzle of browned butter or olive oil and a few chive leaves."),
  ])),
]
