# -*- coding: utf-8 -*-
# Cápsulas de cocina de Celestia. Cada artículo tiene versión ES y EN.
# Bloques: ("p", texto) · ("h2", texto) · ("ul", [items]) · ("ol", [items])
#          ("tabla", [encabezados], [[fila], ...]) · ("tip", texto) · ("dato", texto)

CATS = {
    "cortes":   {"es": "Cortes y técnica", "en": "Knife work & technique", "icono": "🔪"},
    "salsas":   {"es": "Salsas",           "en": "Sauces",                 "icono": "🥄"},
    "carnes":   {"es": "Carnes",           "en": "Meat",                   "icono": "🥩"},
    "emplatado":{"es": "Emplatado",        "en": "Plating",                "icono": "✨"},
    "recetas":  {"es": "Recetas con toque de chef", "en": "Recipes with a chef's touch", "icono": "🍳"},
    "experiencias": {"es": "Chef privado", "en": "Private chef", "icono": "🍽️"},
}

ARTICULOS = [
# ───────────────────────────────────────────────────────────────────────────
dict(slug="cortes-de-cuchillo-y-coccion", cat="cortes", fecha="2026-10-08",
 img="photo-1492739159057-7d1896b3c63f", foto="Caroline Attwood",
 es=dict(
  titulo="Cortes de cuchillo: cómo el corte define la cocción",
  bajada="Brunoise, juliana, mirepoix… no es un capricho de escuela: el tamaño del corte decide cuánto tarda, cuánto sabor suelta y cómo se ve el plato.",
  cuerpo=[
   ("p","Una misma zanahoria puede deshacerse en una salsa o quedar firme en un guiso de cuatro horas. La diferencia no está en el fuego: está en el cuchillo. Cuanto más chico el corte, más superficie expuesta al calor, más rápido se cocina y más sabor entrega al líquido."),
   ("h2","Los cortes clásicos y para qué sirve cada uno"),
   ("tabla",["Corte","Medida aproximada","Ideal para"],[
     ["Brunoise","Cubos de 2 a 3 mm","Salsas, sofritos delicados, terminaciones"],
     ["Macedonia","Cubos de 5 mm","Ensaladas, rellenos, guarniciones"],
     ["Parmentier","Cubos de 1 a 1,2 cm","Papas salteadas, guisos"],
     ["Juliana","Bastones de 2 mm × 5 cm","Salteados rápidos, wok, decoración"],
     ["Bastón","Bastones de 6 mm × 6 cm","Crudités, papas fritas"],
     ["Paysanne","Láminas de 1 × 1 cm, finas","Sopas y cocciones cortas"],
     ["Chiffonade","Tiras muy finas de hojas","Albahaca, espinaca, terminación"],
     ["Mirepoix","Trozos de 1 a 2 cm","Fondos, caldos y braseados largos"],
   ]),
   ("dato","Las medidas varían un poco según la escuela; lo importante es la lógica: cocción larga, corte grande; cocción corta, corte chico."),
   ("h2","La regla de oro: cocción larga, corte grande"),
   ("p","Para un fondo que hierve horas, el mirepoix grande suelta sabor de a poco y no se deshace. Si usaras brunoise, a la media hora sería puré y el caldo quedaría turbio. Al revés, en un salteado de dos minutos solo llegan a cocinarse la juliana o la brunoise."),
   ("tip","Uniformidad antes que velocidad. Si todos los cubos miden lo mismo, todos se cocinan al mismo tiempo. Cortá primero en láminas parejas, después en bastones y recién ahí en cubos: así salen iguales sin esfuerzo."),
   ("h2","Errores que delatan al cocinero apurado"),
   ("ul",["Cortar en tamaños distintos: unos quedan crudos y otros pasados.",
          "Usar un cuchillo sin filo: aplasta en lugar de cortar y la verdura pierde jugo.",
          "Poner todo junto en la sartén: lo duro (zanahoria) va antes que lo tierno (zucchini).",
          "Olvidar la “garra”: los dedos de la mano que sostiene, curvados hacia adentro, guían la hoja y te protegen."]),
  ]),
 en=dict(
  titulo="Knife cuts: how the cut shapes the cooking",
  bajada="Brunoise, julienne, mirepoix… it isn't culinary-school fussiness: the size of the cut decides how long it takes, how much flavor it releases and how the plate looks.",
  cuerpo=[
   ("p","The same carrot can melt into a sauce or stay firm through a four-hour stew. The difference isn't the heat — it's the knife. The smaller the cut, the more surface exposed to heat, the faster it cooks and the more flavor it gives to the liquid."),
   ("h2","The classic cuts and what each one is for"),
   ("tabla",["Cut","Approximate size","Best for"],[
     ["Brunoise","2–3 mm cubes","Sauces, delicate sofritos, finishing"],
     ["Macédoine","5 mm cubes","Salads, fillings, sides"],
     ["Parmentier","1–1.2 cm cubes","Sautéed potatoes, stews"],
     ["Julienne","2 mm × 5 cm sticks","Quick stir-fries, wok, garnish"],
     ["Bâtonnet","6 mm × 6 cm sticks","Crudités, fries"],
     ["Paysanne","Thin 1 × 1 cm slices","Soups and short cooking"],
     ["Chiffonade","Very thin ribbons of leaves","Basil, spinach, finishing"],
     ["Mirepoix","1–2 cm pieces","Stocks, broths and long braises"],
   ]),
   ("dato","Sizes vary slightly from school to school; what matters is the logic: long cooking, big cut; short cooking, small cut."),
   ("h2","The golden rule: long cooking, big cut"),
   ("p","For a stock that simmers for hours, a large mirepoix releases flavor slowly and doesn't fall apart. With a brunoise it would be mush in half an hour and the stock would turn cloudy. Conversely, in a two-minute stir-fry only a julienne or brunoise has time to cook."),
   ("tip","Consistency before speed. If every cube is the same size, they all cook at the same time. Slice evenly first, then cut into sticks, and only then into cubes: they come out identical without effort."),
   ("h2","Mistakes that give away a rushed cook"),
   ("ul",["Cutting different sizes: some stay raw while others overcook.",
          "Using a dull knife: it crushes instead of cutting and the vegetable loses its juice.",
          "Adding everything at once: hard vegetables (carrot) go in before tender ones (zucchini).",
          "Forgetting the “claw”: the fingers of your holding hand, curled inward, guide the blade and keep you safe."]),
  ])),
# ───────────────────────────────────────────────────────────────────────────
dict(slug="las-5-salsas-madre", cat="salsas", fecha="2026-10-08",
 img="photo-1625631976982-c6df1654a6ea", foto="Vitor Monthay",
 es=dict(
  titulo="Las 5 salsas madre: la base de casi todas las salsas",
  bajada="Dominá cinco salsas y tenés la llave de cientos de variantes. Así las ordenó la cocina francesa y así se siguen enseñando en las escuelas.",
  cuerpo=[
   ("p","A principios del siglo XX, Auguste Escoffier ordenó las salsas de la cocina francesa en cinco “madres”. De cada una nacen las “hijas” o derivadas: cambiás un ingrediente o sumás una terminación y tenés una salsa nueva."),
   ("tabla",["Salsa madre","Base","Espesante","Algunas derivadas"],[
     ["Bechamel","Leche","Roux blanco","Mornay (con queso), Soubise (con cebolla)"],
     ["Velouté","Fondo claro (ave, ternera o pescado)","Roux rubio","Suprema (con crema), Allemande (con yema)"],
     ["Española","Fondo oscuro, mirepoix y tomate","Roux oscuro","Demi-glace, bordelesa"],
     ["Holandesa","Yemas y manteca clarificada","Emulsión","Bearnesa (estragón), Muselina (crema batida)"],
     ["Tomate","Tomate, aromáticos y fondo","Reducción","Provenzal, criolla"],
   ]),
   ("h2","El roux, el secreto de tres de las cinco"),
   ("p","El roux es manteca y harina en igual peso, cocinadas juntas. Según cuánto lo cocines cambia el color y el sabor: blanco (2 a 3 minutos), rubio (unos 5) u oscuro (hasta color avellana). Cuanto más oscuro, más sabor tostado pero menos poder de espesar."),
   ("dato","Como referencia, unos 50 g de manteca y 50 g de harina espesan 1 litro de leche para una bechamel de consistencia media."),
   ("tip","Contraste de temperaturas: roux caliente con líquido frío, o roux frío con líquido caliente. Nunca los dos calientes: es la forma más segura de que no se formen grumos. Batí con batidor, no con cuchara."),
   ("h2","La holandesa, la más delicada"),
   ("p","No lleva harina: es una emulsión de yemas y manteca, como una mayonesa tibia. Se hace a baño María, batiendo las yemas con un poco de agua o reducción hasta que espesan, y sumando la manteca clarificada de a hilo. Si se calienta de más, las yemas se cocinan y se corta."),
   ("tip","Si la holandesa se corta, no la tires: en otro bol poné una yema o una cucharada de agua tibia y volvé a incorporar la salsa cortada de a poco, batiendo. Se recupera."),
   ("h2","Cómo hacerte ver como chef con esto"),
   ("ul",["Una bechamel con un poco de queso rallado al final ya es una Mornay: ideal para gratinar.",
          "Una velouté de ave con crema y unas gotas de limón es una suprema para pollo o pescado.",
          "Una holandesa con estragón, chalota y vinagre reducido es una bearnesa: el clásico para un buen bife."]),
  ]),
 en=dict(
  titulo="The 5 mother sauces: the base of almost every sauce",
  bajada="Master five sauces and you hold the key to hundreds of variations. That's how French cuisine organized them, and it's still how culinary schools teach them.",
  cuerpo=[
   ("p","In the early 20th century, Auguste Escoffier organized the sauces of French cuisine into five “mothers.” Each one gives birth to “daughter” or derivative sauces: change one ingredient or add a finish and you have a new sauce."),
   ("tabla",["Mother sauce","Base","Thickener","Some derivatives"],[
     ["Béchamel","Milk","White roux","Mornay (with cheese), Soubise (with onion)"],
     ["Velouté","Light stock (chicken, veal or fish)","Blond roux","Suprême (with cream), Allemande (with yolk)"],
     ["Espagnole","Brown stock, mirepoix and tomato","Brown roux","Demi-glace, bordelaise"],
     ["Hollandaise","Egg yolks and clarified butter","Emulsion","Béarnaise (tarragon), Mousseline (whipped cream)"],
     ["Tomato","Tomato, aromatics and stock","Reduction","Provençal, creole"],
   ]),
   ("h2","Roux, the secret behind three of the five"),
   ("p","Roux is butter and flour in equal weight, cooked together. How long you cook it changes the color and flavor: white (2 to 3 minutes), blond (about 5) or brown (until hazelnut-colored). The darker it is, the more toasty flavor but the less thickening power."),
   ("dato","As a guide, about 50 g butter and 50 g flour thicken 1 liter of milk for a medium-consistency béchamel."),
   ("tip","Contrast the temperatures: hot roux with cold liquid, or cold roux with hot liquid. Never both hot: it's the surest way to avoid lumps. Use a whisk, not a spoon."),
   ("h2","Hollandaise, the most delicate"),
   ("p","It has no flour: it's an emulsion of yolks and butter, like a warm mayonnaise. It's made over a bain-marie, whisking the yolks with a little water or reduction until they thicken, then adding clarified butter in a thin stream. If it gets too hot, the yolks cook and it splits."),
   ("tip","If your hollandaise splits, don't throw it away: put a yolk or a spoonful of warm water in another bowl and whisk the split sauce back in little by little. It comes back."),
   ("h2","How to look like a chef with this"),
   ("ul",["A béchamel with a little grated cheese at the end is already a Mornay: perfect for gratins.",
          "A chicken velouté with cream and a few drops of lemon is a suprême for chicken or fish.",
          "A hollandaise with tarragon, shallot and reduced vinegar is a béarnaise: the classic for a good steak."]),
  ])),
# ───────────────────────────────────────────────────────────────────────────
dict(slug="ojo-de-bife-sellado-punto-reposo", cat="carnes", fecha="2026-10-08",
 img="photo-1529692236671-f1f6cf9683ba", foto="José Ignacio Pompé",
 es=dict(
  titulo="Ojo de bife: sellado, punto y reposo",
  bajada="Tres decisiones separan un bife común de uno de restaurante: cómo lo sellás, cuándo lo sacás y cuánto lo dejás descansar.",
  cuerpo=[
   ("h2","Antes del fuego"),
   ("ul",["Sacalo de la heladera 30 a 40 minutos antes: si entra helado, se pasa por fuera antes de llegar al punto por dentro.",
          "Secalo bien con papel: la humedad hace que se hierva en lugar de dorarse.",
          "Salá con anticipación (40 minutos o más) o justo antes de cocinar."]),
   ("h2","El sellado"),
   ("p","Sartén de hierro o plancha bien caliente, con un hilo de aceite neutro. El bife tiene que chirriar al apoyarlo. Esa costra dorada es la reacción de Maillard: azúcares y proteínas que se transforman en cientos de compuestos de sabor. No lo muevas hasta que se despegue solo."),
   ("tip","El arroser: en el último minuto bajá el fuego, sumá una cucharada de manteca, un diente de ajo aplastado y una rama de tomillo, inclinás la sartén y lo bañás con la manteca espumosa usando una cuchara. Es el gesto que más sabor suma en menos tiempo."),
   ("h2","El punto, con termómetro"),
   ("p","El tacto engaña; el termómetro no. Medí en el centro de la pieza y retirá del fuego unos 3 °C antes del punto que buscás, porque la temperatura sigue subiendo mientras reposa."),
   ("tabla",["Punto","Temperatura final aproximada","Cómo se ve"],[
     ["Jugoso","52 – 54 °C","Centro rojo y tibio"],
     ["A punto","56 – 58 °C","Centro rosado, jugoso"],
     ["Tres cuartos","60 – 63 °C","Apenas rosado"],
     ["Cocido","65 °C o más","Sin rosado"],
   ]),
   ("h2","El reposo, el paso que todos saltean"),
   ("p","Dejalo descansar 5 a 8 minutos sobre una rejilla o tabla, sin tapar con fuerza. Las fibras se relajan y los jugos se redistribuyen: si lo cortás enseguida, terminan en la tabla y no en el plato."),
   ("tip","Cortá en contra de la fibra, en láminas, y terminá con sal en escamas recién al servir: el crocante de la sal sobre la carne tibia es pura terminación de chef."),
  ]),
 en=dict(
  titulo="Ribeye: sear, doneness and rest",
  bajada="Three decisions separate an ordinary steak from a restaurant one: how you sear it, when you take it off and how long you let it rest.",
  cuerpo=[
   ("h2","Before the heat"),
   ("ul",["Take it out of the fridge 30 to 40 minutes before: if it goes in cold, the outside overcooks before the inside reaches doneness.",
          "Pat it very dry with paper: moisture makes it boil instead of brown.",
          "Salt well ahead (40 minutes or more) or right before cooking."]),
   ("h2","The sear"),
   ("p","A cast-iron pan or griddle, very hot, with a drizzle of neutral oil. The steak should sizzle loudly when it lands. That golden crust is the Maillard reaction: sugars and proteins transforming into hundreds of flavor compounds. Don't move it until it releases on its own."),
   ("tip","Basting (arroser): in the last minute lower the heat, add a spoonful of butter, a crushed garlic clove and a sprig of thyme, tilt the pan and spoon the foaming butter over the steak. It's the gesture that adds the most flavor in the least time."),
   ("h2","Doneness, with a thermometer"),
   ("p","Touch can fool you; a thermometer can't. Measure in the center and take it off the heat about 3 °C before your target, because the temperature keeps rising while it rests."),
   ("tabla",["Doneness","Approximate final temperature","How it looks"],[
     ["Rare","52 – 54 °C","Red, warm center"],
     ["Medium-rare","56 – 58 °C","Pink, juicy center"],
     ["Medium","60 – 63 °C","Barely pink"],
     ["Well done","65 °C or more","No pink"],
   ]),
   ("h2","Resting, the step everyone skips"),
   ("p","Let it rest 5 to 8 minutes on a rack or board, loosely covered at most. The fibers relax and the juices redistribute: cut it right away and they end up on the board instead of on the plate."),
   ("tip","Slice against the grain and finish with flaky salt only when serving: the crunch of salt on warm meat is a true chef's finish."),
  ])),
# ───────────────────────────────────────────────────────────────────────────
dict(slug="emplatar-como-chef", cat="emplatado", fecha="2026-10-08",
 img="photo-1759277513461-41fde7d24083", foto="Madeline Liu",
 es=dict(
  titulo="Emplatar como en un menú de 7 pasos",
  bajada="La comida entra primero por los ojos. Con cinco reglas simples, un plato casero se ve de restaurante.",
  cuerpo=[
   ("ol",["<b>Plato a la temperatura justa.</b> Tibio para lo caliente (unos minutos en el horno apagado), frío para lo frío. Es lo primero que se nota y lo que menos se ve.",
          "<b>Números impares.</b> Tres vieiras se ven mejor que dos o cuatro. Lo impar genera movimiento.",
          "<b>Altura.</b> Apoyá la proteína sobre la guarnición en lugar de al lado: el plato gana volumen y presencia.",
          "<b>Contraste.</b> De color (un verde fresco sobre algo dorado) y de textura (algo crocante sobre algo cremoso).",
          "<b>Espacio vacío.</b> No llenes el plato. El blanco alrededor enmarca la comida y la hace protagonista."]),
   ("h2","La salsa, con cuchara"),
   ("p","Una cucharada de salsa en el plato, y con el dorso de la cuchara arrastrás en un solo movimiento: la clásica lágrima. Otra opción es un punto de salsa al costado de la proteína, nunca encima tapándola si tiene una costra dorada que mostrar."),
   ("tip","Tené a mano una servilleta apenas húmeda y una pinza. Antes de servir, repasá el borde del plato: una gota de salsa o una miga en el borde es lo que separa un plato casero de uno de chef."),
   ("h2","La terminación"),
   ("ul",["Un hilo de buen aceite de oliva o de aceite de hierbas.",
          "Sal en escamas sobre la proteína.",
          "Hojas pequeñas o brotes, con pinza, en dos o tres puntos — no como lluvia.",
          "Ralladura de cítrico justo antes de llevar a la mesa."]),
   ("dato","En un menú por pasos, cada plato se piensa como una composición: el orden, el color y el ritmo de toda la cena importan tanto como cada plato por separado."),
  ]),
 en=dict(
  titulo="Plating like a 7-course tasting menu",
  bajada="We eat with our eyes first. With five simple rules, a home-cooked dish looks restaurant-ready.",
  cuerpo=[
   ("ol",["<b>The right plate temperature.</b> Warm for hot food (a few minutes in a switched-off oven), chilled for cold food. It's the first thing you notice and the least visible.",
          "<b>Odd numbers.</b> Three scallops look better than two or four. Odd numbers create movement.",
          "<b>Height.</b> Rest the protein on top of the side instead of next to it: the plate gains volume and presence.",
          "<b>Contrast.</b> Of color (a fresh green over something golden) and texture (something crunchy over something creamy).",
          "<b>Empty space.</b> Don't fill the plate. The white around it frames the food and makes it the star."]),
   ("h2","Sauce, with a spoon"),
   ("p","A spoonful of sauce on the plate, then drag it with the back of the spoon in one movement: the classic swoosh. Another option is a dot of sauce beside the protein — never on top, hiding a golden crust worth showing."),
   ("tip","Keep a barely damp cloth and tweezers at hand. Before serving, wipe the rim: a drop of sauce or a crumb on the edge is what separates a home plate from a chef's."),
   ("h2","The finish"),
   ("ul",["A drizzle of good olive oil or herb oil.",
          "Flaky salt on the protein.",
          "Small leaves or sprouts, placed with tweezers at two or three points — not scattered like rain.",
          "Citrus zest right before it goes to the table."]),
   ("dato","In a tasting menu, each plate is designed as a composition: the order, color and rhythm of the whole dinner matter as much as each plate on its own."),
  ])),
# ───────────────────────────────────────────────────────────────────────────
dict(slug="reducciones-y-glaseados", cat="salsas", fecha="2026-10-08",
 img="photo-1499126167718-c87f5c1387e8", foto="Caroline Attwood",
 es=dict(
  titulo="Reducciones y glaseados: el brillo de restaurante",
  bajada="Ese brillo espejado de las salsas de restaurante no es magia: es reducción, paciencia y manteca fría al final.",
  cuerpo=[
   ("h2","Desglasar: el sabor está pegado en la sartén"),
   ("p","Después de sellar una carne quedan restos dorados en el fondo de la sartén. Eso es sabor concentrado. Sacá la carne, volcá un chorro de vino, fondo o incluso agua, y raspá con una cuchara de madera mientras hierve: todo ese dorado se disuelve y se convierte en la base de tu salsa."),
   ("h2","Reducir hasta “napar”"),
   ("p","Dejá hervir suave hasta que el líquido se reduzca y tome cuerpo. El punto se llama napar: cuando la salsa cubre el dorso de una cuchara y, si pasás el dedo, la línea queda marcada sin que se junte."),
   ("tip","Salá siempre al final. Al reducir, el agua se evapora pero la sal se queda: si salás al principio, al terminar la salsa puede quedar salada de más."),
   ("h2","Montar con manteca: el toque final"),
   ("p","Fuera del fuego, sumá unos cubos de manteca bien fría y movés la sartén en círculos (o batís suave) hasta que se integren. La salsa gana brillo, cuerpo y una textura sedosa. Los franceses lo llaman monter au beurre."),
   ("dato","La manteca tiene que estar fría y la salsa caliente pero sin hervir: si hierve después de montarla, la emulsión se rompe y la manteca se separa."),
   ("h2","Glaseado de vegetales"),
   ("p","Zanahorias, cebollitas o nabos con agua hasta la mitad, una cucharada de manteca, una pizca de azúcar y sal. Cocinás a fuego medio hasta que el agua se evapora y queda una película brillante que los envuelve. Si los dejás un minuto más, se doran: glaseado oscuro."),
   ("tip","Pasá la salsa por un colador fino antes de servir. Es un paso de diez segundos que la deja lisa y profesional."),
  ]),
 en=dict(
  titulo="Reductions and glazes: restaurant shine",
  bajada="That mirror-like shine of restaurant sauces isn't magic: it's reduction, patience and cold butter at the end.",
  cuerpo=[
   ("h2","Deglazing: the flavor is stuck to the pan"),
   ("p","After searing meat, golden bits are left on the bottom of the pan. That's concentrated flavor. Take the meat out, pour in a splash of wine, stock or even water, and scrape with a wooden spoon as it boils: all that browning dissolves and becomes the base of your sauce."),
   ("h2","Reducing until it “naps”"),
   ("p","Let it simmer until the liquid reduces and gains body. The point is called nappe: when the sauce coats the back of a spoon and, if you run your finger through it, the line stays without closing up."),
   ("tip","Always salt at the end. As it reduces, the water evaporates but the salt stays: salt at the start and the finished sauce may end up too salty."),
   ("h2","Mounting with butter: the final touch"),
   ("p","Off the heat, add a few cubes of very cold butter and swirl the pan (or whisk gently) until they melt in. The sauce gains shine, body and a silky texture. The French call it monter au beurre."),
   ("dato","The butter must be cold and the sauce hot but not boiling: if it boils after mounting, the emulsion breaks and the butter separates."),
   ("h2","Glazed vegetables"),
   ("p","Carrots, pearl onions or turnips with water halfway up, a spoonful of butter, a pinch of sugar and salt. Cook over medium heat until the water evaporates and leaves a shiny film coating them. Give them one more minute and they brown: a dark glaze."),
   ("tip","Strain the sauce through a fine sieve before serving. It's a ten-second step that leaves it smooth and professional."),
  ])),
# ───────────────────────────────────────────────────────────────────────────
dict(slug="pure-de-papas-de-restaurante", cat="recetas", fecha="2026-10-08",
 img="photo-1585508659081-04a1788941c1", foto="Anna Stampfli",
 es=dict(
  titulo="Puré de papas de restaurante",
  bajada="El acompañamiento más simple es también el que más delata la técnica. Cinco claves para un puré liso, sedoso y con sabor.",
  cuerpo=[
   ("h2","Ingredientes (4 porciones)"),
   ("ul",["1 kg de papas harinosas (papa negra, Spunta)",
          "100 a 150 g de manteca bien fría, en cubos",
          "200 ml de leche (o mitad leche, mitad crema)",
          "Sal, pimienta blanca y nuez moscada"]),
   ("h2","Paso a paso"),
   ("ol",["<b>Agua fría y con sal.</b> Poné las papas (enteras con piel o en trozos parejos) en agua fría con sal y llevá a hervor. Si arrancan en agua hirviendo, se cocinan por fuera antes que por dentro.",
          "<b>Cocción justa.</b> Están listas cuando un cuchillo entra sin resistencia. Escurrí bien.",
          "<b>Secarlas.</b> Volvé las papas a la olla y 1 minuto a fuego bajo, moviendo: se evapora el agua que queda y el puré no se aguachenta.",
          "<b>Pisar, nunca licuar.</b> Pasalas por pisapapas o, mejor, por un tamiz. La minipimer rompe el almidón y el puré se vuelve un engrudo elástico.",
          "<b>Primero la manteca, después la leche.</b> Incorporá la manteca fría en cubos, mezclando, y recién después la leche bien caliente de a poco, hasta la textura que te guste. Condimentá al final."]),
   ("tip","Infusioná la leche: calentala con una hoja de laurel y un diente de ajo aplastado, dejá reposar 10 minutos y colá. Usá pimienta blanca en vez de negra para que no se vean puntitos: es un detalle muy de restaurante."),
   ("dato","Las versiones más famosas de restaurante llevan muchísima más manteca: hasta casi la mitad del peso de las papas. Con 100 a 150 g por kilo tenés un puré de lujo, sin exagerar."),
   ("h2","Para servirlo como chef"),
   ("p","Una cucharada generosa en el centro del plato, y con el dorso de la cuchara hacés una curva que deje un surco. Ahí va la salsa o el jugo de la carne. Arriba, un hilo de manteca dorada o de aceite de oliva y unas hojas de cebollín."),
  ]),
 en=dict(
  titulo="Restaurant-style mashed potatoes",
  bajada="The simplest side is also the one that most reveals technique. Five keys to a smooth, silky, flavorful mash.",
  cuerpo=[
   ("h2","Ingredients (4 servings)"),
   ("ul",["1 kg floury potatoes",
          "100 to 150 g very cold butter, cubed",
          "200 ml milk (or half milk, half cream)",
          "Salt, white pepper and nutmeg"]),
   ("h2","Step by step"),
   ("ol",["<b>Cold, salted water.</b> Put the potatoes (whole with skin, or in even pieces) in cold salted water and bring to a boil. If they start in boiling water, the outside cooks before the inside.",
          "<b>Just-right cooking.</b> They're ready when a knife slides in without resistance. Drain well.",
          "<b>Dry them.</b> Return the potatoes to the pot for 1 minute over low heat, stirring: the leftover water evaporates and the mash won't be watery.",
          "<b>Mash, never blend.</b> Use a potato ricer or, better, a sieve. A stick blender breaks the starch and turns the mash gluey and elastic.",
          "<b>Butter first, then milk.</b> Work in the cold butter cubes, then add the very hot milk little by little until you like the texture. Season at the end."]),
   ("tip","Infuse the milk: heat it with a bay leaf and a crushed garlic clove, let it sit 10 minutes and strain. Use white pepper instead of black so there are no specks: a very restaurant detail."),
   ("dato","The most famous restaurant versions use far more butter: up to nearly half the weight of the potatoes. With 100 to 150 g per kilo you get a luxurious mash without going overboard."),
   ("h2","To serve it like a chef"),
   ("p","A generous spoonful in the center of the plate, then sweep a curve with the back of the spoon to leave a groove. That's where the sauce or meat juices go. On top, a drizzle of browned butter or olive oil and a few chive leaves."),
  ])),
# ────────────────────────────────────────────────────────────────────────
dict(slug="cuanto-cuesta-un-chef-privado-en-buenos-aires", cat="experiencias", fecha="2026-10-09",
 img="photo-1414235077428-338989a2e8c0", foto="Jay Wennington",
 es=dict(
  titulo="¿Cuánto cuesta un chef privado en Buenos Aires?",
  bajada="Qué incluye el precio, qué lo hace variar y valores de referencia para una cena de 3 o 7 pasos en tu casa.",
  cuerpo=[
   ("p","Contratar un chef privado no es pagar solo la comida: es una cena de restaurante en tu casa, sin compras, sin cocinar y sin lavar. Por eso el precio depende menos del plato y más de tres cosas: <b>cuántos pasos tiene el menú, cuántas personas son y qué día es</b>."),
   ("h2","Qué incluye el precio"),
   ("ul",["El diseño del menú a medida, con tus gustos y restricciones.",
          "Las compras y los ingredientes.",
          "La cocina en vivo en tu casa y la presentación de cada paso.",
          "Asistentes de servicio cuando el grupo lo necesita (desde 3 personas uno, desde 9 dos).",
          "El traslado dentro de CABA y Gran Buenos Aires."]),
   ("dato","Las bebidas suelen quedar a cargo del anfitrión. Lo habitual es que el chef sugiera un maridaje para que elijas los vinos."),
   ("h2","Valores de referencia en Celestia"),
   ("p","Estos son los precios con todo incluido (servicio, asistentes e ingredientes) a octubre de 2026, de lunes a viernes al mediodía:"),
   ("tabla",["Personas","Menú de 3 pasos","Degustación de 7 pasos"],[
     ["2","$480.000","$720.000"],["4","$620.000","$900.000"],["6","$810.000","$1.200.000"],["8","$1.000.000","$1.500.000"],["12","$1.480.000","$2.200.000"]]),
   ("p","Viernes a la noche, sábados y domingos el servicio tiene un recargo del 10%. Podés calcular tu caso exacto en la <a href=\"/?reservar=3\">calculadora de la web</a>."),
   ("h2","Qué hace variar el precio"),
   ("ul",["<b>Cantidad de pasos:</b> una degustación de 7 pasos lleva más técnica, más tiempo y más producto que una cena de 3.",
          "<b>Cantidad de personas:</b> no escala lineal; el costo por persona baja a medida que crece el grupo.",
          "<b>Ingredientes:</b> un menú con pesca premium o cortes madurados cuesta más que uno de huerta.",
          "<b>Día y horario:</b> fines de semana y fechas especiales tienen más demanda."]),
   ("tip","Si querés cuidar el presupuesto sin resignar la experiencia, elegí un menú de 3 pasos un día de semana y pedí que el principal sea el plato estrella. Es la forma más eficiente de tener una cena de restaurante en casa."),
   ("h2","¿Conviene frente a un restaurante?"),
   ("p","Para dos personas, un restaurante de alta cocina con vino suele costar parecido. La diferencia aparece en grupo: en casa no hay traslados, la mesa es solo tuya y el menú se arma a tu medida. Si estás pensando en una ocasión especial, mirá la <a href=\"/cena-romantica-en-casa\">cena romántica en casa</a> o la <a href=\"/menu-degustacion-7-pasos\">degustación de 7 pasos</a>."),
  ]),
 en=dict(
  titulo="How much does a private chef cost in Buenos Aires?",
  bajada="What the price includes, what changes it, and reference prices for a 3 or 7-course dinner at home.",
  cuerpo=[
   ("p","Hiring a private chef is not just paying for food: it is a restaurant dinner at home, with no shopping, cooking or dishes. That's why the price depends less on the dish and more on three things: <b>how many courses, how many guests and which day</b>."),
   ("h2","What the price includes"),
   ("ul",["A tailor-made menu designed around your tastes and dietary needs.","Shopping and ingredients.","Live cooking at your home and the presentation of each course.","Service assistants when the group needs them (one from 3 guests, two from 9).","Travel within Buenos Aires City and Greater Buenos Aires."]),
   ("dato","Drinks are usually on the host. The chef typically suggests a pairing so you can choose the wines."),
   ("h2","Reference prices at Celestia"),
   ("p","All-inclusive prices (service, assistants and ingredients) as of October 2026, Monday to Friday lunch:"),
   ("tabla",["Guests","3-course menu","7-course tasting"],[["2","$480,000","$720,000"],["4","$620,000","$900,000"],["6","$810,000","$1,200,000"],["8","$1,000,000","$1,500,000"],["12","$1,480,000","$2,200,000"]]),
   ("p","Friday night, Saturday and Sunday carry a 10% surcharge on the service. You can calculate your exact case with the <a href=\"/?reservar=3\">calculator on the site</a>."),
   ("h2","What changes the price"),
   ("ul",["<b>Number of courses:</b> a 7-course tasting takes more technique, time and produce than a 3-course dinner.","<b>Number of guests:</b> it doesn't scale linearly; the cost per person drops as the group grows.","<b>Ingredients:</b> premium fish or aged cuts cost more than a garden menu.","<b>Day and time:</b> weekends and special dates are in higher demand."]),
   ("tip","To keep the budget in check without losing the experience, choose a 3-course menu on a weekday and make the main the star dish. It is the most efficient way to have a restaurant dinner at home."),
   ("h2","Is it worth it compared to a restaurant?"),
   ("p","For two people, a fine-dining restaurant with wine usually costs about the same. The difference shows in groups: at home there is no travel, the table is all yours and the menu is made to measure. For a special occasion, see the <a href=\"/cena-romantica-en-casa\">romantic dinner at home</a> or the <a href=\"/menu-degustacion-7-pasos\">7-course tasting</a>."),
  ])),
# ────────────────────────────────────────────────────────────────────────
dict(slug="chef-privado-o-catering", cat="experiencias", fecha="2026-10-09",
 img="photo-1555244162-803834f70033", foto="Saile Ilyas",
 es=dict(
  titulo="Chef privado o catering: cuál conviene para tu evento",
  bajada="Las dos opciones resuelven la comida, pero no son lo mismo. Diferencias en experiencia, cantidad de invitados y presupuesto.",
  cuerpo=[
   ("p","Cuando organizás un cumpleaños, una cena con clientes o una celebración en casa, aparecen dos caminos: contratar un catering o traer un chef privado. Los dos te sacan la cocina de encima, pero la experiencia que viven tus invitados es muy distinta."),
   ("h2","La diferencia en una línea"),
   ("p","<b>El catering lleva la comida hecha; el chef privado cocina en tu casa.</b> Con catering recibís bandejas listas para servir. Con un chef, cada plato se termina y se emplata en el momento, frente a tus invitados."),
   ("tabla",["","Chef privado","Catering"],[
     ["Dónde se cocina","En tu cocina, en vivo","En su cocina, antes del evento"],
     ["Formato","Menú de pasos servido a la mesa","Bandejas, buffet o finger food"],
     ["Grupo ideal","2 a 12 personas (más, a medida)","Grupos grandes"],
     ["Personalización","Total: menú a medida","Sobre una carta fija"],
     ["Experiencia","Cena de restaurante en casa","Comida resuelta"]]),
   ("h2","Cuándo conviene un chef privado"),
   ("ul",["Cenas íntimas, aniversarios o cumpleaños de pocos invitados.",
          "Cenas con clientes donde la experiencia también comunica.",
          "Cuando querés un menú de pasos y no una mesa de bandejas.",
          "Si hay restricciones alimentarias que necesitan cuidado especial."]),
   ("h2","Cuándo conviene un catering"),
   ("ul",["Eventos grandes donde la gente circula y come de pie.",
          "Cuando no hay cocina disponible en el lugar.",
          "Si el foco está en la cantidad más que en la experiencia gastronómica."]),
   ("tip","Hay un punto medio: para grupos de más de 12 personas podés armar un evento a medida con chef y staff de servicio, con estaciones o finger food cocinados en el lugar. Es catering con sabor de restaurante."),
   ("p","Si tu evento es para un grupo chico, mirá la <a href=\"/menu-degustacion-7-pasos\">degustación de 7 pasos</a>. Si es más grande o corporativo, contame la idea en <a href=\"/eventos-corporativos\">eventos y empresas</a>."),
  ]),
 en=dict(
  titulo="Private chef or catering: which one fits your event",
  bajada="Both take care of the food, but they are not the same. Differences in experience, guest count and budget.",
  cuerpo=[
   ("p","When you plan a birthday, a client dinner or a celebration at home, two paths appear: hire a caterer or bring in a private chef. Both take the kitchen off your hands, but your guests' experience is very different."),
   ("h2","The difference in one line"),
   ("p","<b>Catering brings the food ready-made; a private chef cooks at your home.</b> With catering you get trays ready to serve. With a chef, each dish is finished and plated on the spot, in front of your guests."),
   ("tabla",["","Private chef","Catering"],[["Where it's cooked","In your kitchen, live","In their kitchen, beforehand"],["Format","Plated courses at the table","Trays, buffet or finger food"],["Ideal group","2 to 12 guests (more, custom)","Large groups"],["Customization","Full: tailor-made menu","From a set menu"],["Experience","Restaurant dinner at home","Food taken care of"]]),
   ("h2","When a private chef makes sense"),
   ("ul",["Intimate dinners, anniversaries or small birthdays.","Client dinners where the experience also sends a message.","When you want a coursed menu, not a table of trays.","If there are dietary restrictions that need special care."]),
   ("h2","When catering makes sense"),
   ("ul",["Large events where people mingle and eat standing.","When there is no kitchen at the venue.","If the focus is on quantity more than on the dining experience."]),
   ("tip","There's a middle ground: for groups over 12 you can plan a custom event with a chef and service staff, with stations or finger food cooked on site. Catering with a restaurant taste."),
   ("p","For a small group, see the <a href=\"/menu-degustacion-7-pasos\">7-course tasting</a>. For something bigger or corporate, tell me the idea in <a href=\"/eventos-corporativos\">events & companies</a>."),
  ])),
# ────────────────────────────────────────────────────────────────────────
dict(slug="como-funciona-un-chef-semanal", cat="experiencias", fecha="2026-10-09",
 img="photo-1543353071-873f17a7a088", foto="Ella Olsson",
 es=dict(
  titulo="Cómo funciona un chef semanal (y si te conviene)",
  bajada="Una o dos jornadas de cocina en tu casa y la semana resuelta. Qué incluye, cuántas horas lleva y cuánto cuesta.",
  cuerpo=[
   ("p","El chef semanal es para quien quiere comer casero y rico toda la semana sin pasarse las noches cocinando. La idea es simple: <b>un chef cocina en tu casa uno o dos días y te deja las comidas listas, fraccionadas y etiquetadas</b>."),
   ("h2","Cómo es una semana"),
   ("ol",["Armamos el menú por WhatsApp con tus gustos, rutinas y restricciones.",
          "El día acordado cocino en tu casa, con tu cocina y tus utensilios.",
          "Dejo todo fraccionado y etiquetado, con indicaciones de qué va a la heladera y qué conviene congelar.",
          "Durante la semana solo calentás y servís."]),
   ("h2","2 o 5 comidas por día"),
   ("tabla",["Opción","Qué incluye","Jornada"],[
     ["2 comidas por día","Almuerzo y cena","~8 horas"],
     ["5 comidas por día","Desayuno, almuerzo, merienda, cena y postre","~12 horas"]]),
   ("p","Con una jornada cubrís media semana; con dos, la semana completa. Para 1 a 2 personas, una jornada de 2 comidas por día arranca en $160.000 (honorario del servicio; los ingredientes se coordinan aparte). Podés ver todos los valores en <a href=\"/chef-semanal\">chef semanal</a>."),
   ("tip","Pedí que al menos una preparación por jornada sea \"base\": un guiso, una salsa o legumbres que rindan para combinar con distintas guarniciones. Es el truco para que la semana no se sienta repetida."),
   ("h2","¿Para quién es?"),
   ("ul",["Familias con poco tiempo entre semana.",
          "Personas que quieren comer mejor y dejar el delivery.",
          "Quien sigue una alimentación específica y necesita orden.",
          "Parejas que prefieren invertir el tiempo en otra cosa."]),
   ("dato","La cocina hogareña alcanza: hornallas, horno, heladera con espacio y recipientes. Si faltan recipientes, lo coordinamos antes."),
  ]),
 en=dict(
  titulo="How a weekly chef works (and whether it suits you)",
  bajada="One or two cooking sessions at your home and the week sorted. What it includes, how many hours it takes and what it costs.",
  cuerpo=[
   ("p","A weekly chef is for people who want to eat tasty home food all week without spending their evenings cooking. The idea is simple: <b>a chef cooks at your home one or two days and leaves your meals ready, portioned and labeled</b>."),
   ("h2","What a week looks like"),
   ("ol",["We plan the menu on WhatsApp around your tastes, routines and dietary needs.","On the agreed day I cook at your home, with your kitchen and utensils.","I leave everything portioned and labeled, noting what goes in the fridge and what is best frozen.","During the week you just heat and serve."]),
   ("h2","2 or 5 meals a day"),
   ("tabla",["Option","What it includes","Session"],[["2 meals a day","Lunch and dinner","~8 hours"],["5 meals a day","Breakfast, lunch, afternoon snack, dinner and dessert","~12 hours"]]),
   ("p","One session covers half the week; two cover the full week. For 1 to 2 people, a session with 2 meals a day starts at $160,000 (service fee; ingredients are coordinated separately). See all prices at <a href=\"/chef-semanal\">weekly chef</a>."),
   ("tip","Ask for at least one \"base\" dish per session: a stew, a sauce or legumes that stretch across different sides. It is the trick to keep the week from feeling repetitive."),
   ("h2","Who is it for?"),
   ("ul",["Families with little time during the week.","People who want to eat better and drop delivery.","Anyone on a specific diet who needs structure.","Couples who'd rather spend their time on something else."]),
   ("dato","A regular home kitchen is enough: burners, an oven, a fridge with space and containers. If containers are missing, we sort it out beforehand."),
  ])),
]
